BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
END;

BEGIN
	DBMS_OUTPUT.PUT('HELLO WORLD!');
	DBMS_OUTPUT.PUT('HOW ARE YOU?');
	DBMS_OUTPUT.PUT_LINE(' I AM FINE');
	DBMS_OUTPUT.PUT('WHAT ABOUT YOU?');
	DBMS_OUTPUT.PUT_LINE('');
END;

DECLARE
	X NUMBER := 52;
	F FLOAT := 63.25;
	CH CHAR := 'A';
	S VARCHAR(25) := 'TOPS';
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF F = '||F);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF CH = '||CH);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF S = '||S);
END;

DECLARE
    NUM1 NUMBER := 5;
	NUM2 NUMBER := 2;
	ANS NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('THE ADDITION IS = '||(NUM1+NUM2));
    DBMS_OUTPUT.PUT_LINE('THE SUBTRACTION IS = '||(NUM1-NUM2));
	DBMS_OUTPUT.PUT_LINE('THE MULTIPLICATION IS = '||(NUM1*NUM2));
    DBMS_OUTPUT.PUT_LINE('THE DIVISION IS = '||(NUM1/NUM2));
    DBMS_OUTPUT.PUT_LINE('THE REMAINDER IS = '||MOD(NUM1,NUM2));
END;

DECLARE
	AGE NUMBER := 19;
BEGIN
	IF AGE>18 THEN
		DBMS_OUTPUT.PUT_LINE('YOU ARE ELIGIBLE FOR VOTING');
	ELSE
		DBMS_OUTPUT.PUT_LINE('YOU ARE NOT ELIGIBLE FOR VOTING');
	END IF;
END;

DECLARE 
	NUM1 NUMBER := 55;
	NUM2 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE
	NUM1 NUMBER := 25;
	NUM2 NUMBER := 35;
	NUM3 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 AND NUM1>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSIF NUM2>NUM1 AND NUM2>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE 
	NUM1 NUMBER := 25;
	NUM2 NUMBER := 35;
	NUM3 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 THEN
		IF NUM1>NUM3 THEN
			DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
		END IF;
	ELSE
		IF NUM2>NUM3 THEN
			DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
		END IF;
	END IF;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');--5
		I := I+1;--6
		IF I = 6 THEN
            EXIT;
		END IF;
	END LOOP;
END;

DECLARE
	NUM1 NUMBER := 1;
	NUM2 NUMBER := 30;
BEGIN
	LOOP
		IF MOD(NUM1,2) = 0 THEN
			DBMS_OUTPUT.PUT_LINE(NUM1);
		END IF;
		NUM1 := NUM1 + 1;
		EXIT WHEN NUM1 = NUM2;
	END LOOP;
END;