BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
END;

BEGIN
	DBMS_OUTPUT.PUT('HELLO WORLD!');
	DBMS_OUTPUT.PUT('HOW ARE YOU?');
	DBMS_OUTPUT.PUT_LINE(' I AM FINE');
	DBMS_OUTPUT.PUT('WHAT ABOUT YOU?');
	DBMS_OUTPUT.PUT_LINE('');
END;

DECLARE
	X NUMBER := 52;
	F FLOAT := 63.25;
	CH CHAR := 'A';
	S VARCHAR(25) := 'TOPS';
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF F = '||F);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF CH = '||CH);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF S = '||S);
END;

DECLARE
    NUM1 NUMBER := 5;
	NUM2 NUMBER := 2;
	ANS NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('THE ADDITION IS = '||(NUM1+NUM2));
    DBMS_OUTPUT.PUT_LINE('THE SUBTRACTION IS = '||(NUM1-NUM2));
	DBMS_OUTPUT.PUT_LINE('THE MULTIPLICATION IS = '||(NUM1*NUM2));
    DBMS_OUTPUT.PUT_LINE('THE DIVISION IS = '||(NUM1/NUM2));
    DBMS_OUTPUT.PUT_LINE('THE REMAINDER IS = '||MOD(NUM1,NUM2));
END;

DECLARE
	AGE NUMBER := 19;
BEGIN
	IF AGE>18 THEN
		DBMS_OUTPUT.PUT_LINE('YOU ARE ELIGIBLE FOR VOTING');
	ELSE
		DBMS_OUTPUT.PUT_LINE('YOU ARE NOT ELIGIBLE FOR VOTING');
	END IF;
END;

DECLARE 
	NUM1 NUMBER := 55;
	NUM2 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE
	NUM1 NUMBER := 25;
	NUM2 NUMBER := 35;
	NUM3 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 AND NUM1>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSIF NUM2>NUM1 AND NUM2>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE 
	NUM1 NUMBER := 25;
	NUM2 NUMBER := 35;
	NUM3 NUMBER := 45;
BEGIN
	IF NUM1>NUM2 THEN
		IF NUM1>NUM3 THEN
			DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
		END IF;
	ELSE
		IF NUM2>NUM3 THEN
			DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
		END IF;
	END IF;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');--5
		I := I+1;--6
		IF I = 6 THEN
            EXIT;
		END IF;
	END LOOP;
END;

DECLARE
	NUM1 NUMBER := 1;
	NUM2 NUMBER := 30;
BEGIN
	LOOP
		IF MOD(NUM1,2) = 0 THEN
			DBMS_OUTPUT.PUT_LINE(NUM1);
		END IF;
		NUM1 := NUM1 + 1;
		EXIT WHEN NUM1 = NUM2;
	END LOOP;
END;

-- FOR LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	FOR X IN 1..30 LOOP
		IF MOD(I,2) != 0 THEN
			DBMS_OUTPUT.PUT_LINE(I);
		END IF;
		I := I+1;
	END LOOP;
END;

BEGIN
	FOR X IN 1..5 LOOP
		DBMS_OUTPUT.PUT_LINE(X||'. HELLO WORLD!');
	END LOOP;
END;

-- WHILE LOOP
DECLARE
	X NUMBER := 1;
BEGIN
	WHILE X<=5 LOOP
		DBMS_OUTPUT.PUT_LINE(X||'. HELLO WORLD');
		X := X + 1;
	END LOOP;
END;

-- EXPLICIT CURSOR
DECLARE
	FNAME EMPLOYEES.FIRST_NAME%TYPE;
	SAL EMPLOYEES.SALARY%TYPE;
	CURSOR EMP IS SELECT FIRST_NAME,SALARY FROM EMPLOYEES;
BEGIN
	OPEN EMP;
	LOOP
		FETCH EMP INTO FNAME,SAL;
		DBMS_OUTPUT.PUT_LINE(FNAME||' GETS '||SAL||' AS A SALARY');
		EXIT WHEN EMP%NOTFOUND;
	END LOOP;
	CLOSE EMP;
END;

-- IMPLICIT CURSOR
DECLARE
	ROW_NUMBER NUMBER := 0;
BEGIN
	UPDATE EMPLOYEES SET SALARY = SALARY + 10000 WHERE DEPARTMENT_ID = 60;
	IF SQL%FOUND THEN
		ROW_NUMBER := SQL%ROWCOUNT;
	ELSE
		DBMS_OUTPUT.PUT_LINE('NO EMPLOYEE DETAILS IS UPDATED');
	END IF;
		DBMS_OUTPUT.PUT_LINE('UPDATED EMPLOYEES = '||ROW_NUMBER);
END;

SELECT * FROM EMPLOYEES;